// <auto-generated />
namespace Instant.Server.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131048105_InitialEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
